version: '3.8'

services:
  app:
    image: node:20-bullseye-slim
    working_dir: /app
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tallman_app
      - PORT=3100
    volumes:
      - .:/app
      - /app/node_modules # Anonymous Volume Shadowing
    ports:
      - "3100:3100"
    command: [ "/bin/bash", "-c", "./docker-entrypoint.sh" ]
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tallman_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
